### PR TITLE
jBCrypt 0.4 update

### PR DESCRIPTION
**Pull request by jordanclark**
I've just pulled in the latest jBCrypt 0.4 bugfix
http://www.mindrot.org/projects/jBCrypt/news/rel04.html

### CODE REVIEW

**Comment by jordanclark** [comment]
This should resolve issue #16

**Comment by JamoCA** [comment]
Just curious as to whether this branch is going to get merged or not.  (It's been 6 years.)  Thanks.

**Comment by jordanclark** [comment]
@JamoCA you can pull from my branch jordanclark/cfpassphrase I'll keep it updated if jbcrypt updates.

**Comment by boughtonp** [comment]
Many thanks Jordan. I'm gradually getting around to sorting things...

I've just pushed a release candidate for 0.2 which has jBCrypt v0.4 included (as well as the relevant OSGI manifest for Lucee 5), and is [available from here](https://www.sorcerersisle.com/software/cfpassphrase).

**Comment by boughtonp** [comment]
Release of cfPassphrase v0.2 includes jBCrypt 0.4

**Pull request closed without merging**
